### ISSUE TITLE
Cannot compute -1/3

### ISSUE THREAD

**Issue by Mortal** [Mortal/pyfrac#1]
```
>>> -1/3
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/ssd/home/.local/bin/pyfrac", line 234, in display_hook
    disp = '%s = %s' % (v, repeated(v))
  File "/ssd/home/.local/bin/pyfrac", line 154, in repeated
    exponent = fraction_floorlog(n, base)
  File "/ssd/home/.local/bin/pyfrac", line 203, in fraction_floorlog
    raise ValueError('log of non-positive')
ValueError: log of non-positive
```

**Comment by Mortal** [comment]
Now works due to @Tyilo's work:

```
>>> -1/3
-1/3 = -0.(3)
```
